views:
  - name: EventPerformanceOverview
    description: "Event sales performance view"
    
    cubes:
      - join_path: FactOrders
        includes: "*"
        
      - join_path: FactOrders.DimEvents
        includes:
          - name
          - start_date
          - status
          - dash_category
        excludes:
          - count
          - company_id
          - currency
          - created_at
          - description
          
      - join_path: FactOrders.DimTickets
        includes:
          - sold_count_total
          - avg_min_price
        excludes:
          - count
          - name
          - company_id
          - currency
          - created_at
          - description
          - event_id