views:
  - name: EventPerformanceOverview
    title: Event Performance Overview
    description: Overview of event performance metrics. It includes all orders transactions, each transactions metadata from the fact FactOrders cube, and event details from the DimEvents cube.
    
    cubes:
      - join_path: FactOrders
        includes:
          - order_id
          - order_date
          - email
          - ticket_id
          - company_id
          - shop_id
          - event_id
          - payment_method
          - currency
          - count
          - total_order_value
          - avg_order_value
          - total_tickets_sold
          - avg_tickets_per_order
        
      - join_path: FactOrders.DimEvents
        includes:
          - name: name
            alias: event_name
          - name: start_date
            alias: event_start_date
          - name: status
            alias: event_status
          - name: dash_category
            alias: event_dash_category
        excludes:
          - count
          - company_id
          - currency
          - created_at
          - description
          