views:
  - name: EventPerformanceOverview
    title: Event Performance Overview
    description: KPIs and attributes to analyze orders, revenue, tickets, payments, and risk at event/shop level.

    cubes:
      # Root fact + core measures/dimensions
      - join_path: FactOrders
        includes:
          # Measures
          - revenues
          - tickets_sold
          - events_count
          - tickets_count
          - avg_revenue_per_event
          - orders_count
          - transactions_count
          - avg_order_value
          - avg_tickets_per_order
          - refund_protect_attach_rate
          - card_orders_share
          # Dimensions
          - order_date
          - event_id
          - shop_id
          - company_id
          - currency
          - payment_method

      # Event attributes
      - join_path: FactOrders.DimEvents
        includes:
          - event_name
          - genre

      # Ticket attributes (kept minimal)
      - join_path: FactOrders.DimTickets
        includes:
          - ticket_name